using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace SegeoMDL2Helper
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        Dictionary<string, string> data;


        public MainWindow()
        {
            InitializeComponent();


            data = new Dictionary<string, string>() {
                {"Account", "&xEA8C;"},
                {"AccountBox", "&xE187;"},
                {"AccountCancel", "&xE1E0;"},
                {"AccountDetailsOutline", "&xE136;"},
                {"AccountFrameOutline", "&xE156;"},
                {"AccountMultiple", "&xE125;"},
                {"AccountOutline", "&xE13D;"},
                {"AccountOutlineBox", "&xE8D4;"},
                {"AccountPlus", "&xE1E2;"},
                {"AccountStatus", "&xE181;"},
                {"AccountSwitch", "&xE748;"},
                {"Airplane", "&xEB4C;"},
                {"AirplaneOutline", "&xE709;"},
                {"Album", "&xE142;"},
                {"Alert", "&xE814;"},
                {"AlertOutline", "&xE7BA;"},
                {"Archive", "&xE7B8;"},
                {"Arrow", "&xE1D1;"},
                {"ArrowBottomRight", "&xE741;"},
                {"ArrowDown", "&xE1FD;"},
                {"ArrowLeft", "&xE0A6;"},
                {"ArrowRight", "&xE0AD;"},
                {"ArrowTopLeft", "&xE742;"},
                {"ArrowUp", "&xE110;"},
                {"ArrowUpVariant", "&xE752;"},
                {"Attach", "&xE16C;"},
                {"Bag", "&xE14D;"},
                {"Battery0", "&xE850;"},
                {"Battery1", "&xE851;"},
                {"Battery10", "&xE83F;"},
                {"Battery2", "&xE852;"},
                {"Battery3", "&xE853;"},
                {"Battery4", "&xE854;"},
                {"Battery5", "&xE855;"},
                {"Battery6", "&xE856;"},
                {"Battery7", "&xE857;"},
                {"Battery8", "&xE858;"},
                {"Battery9", "&xE859;"},
                {"BatteryCharge0", "&xE85A;"},
                {"BatteryCharge1", "&xE85B;"},
                {"BatteryCharge2", "&xE85C;"},
                {"BatteryCharge3", "&xE85D;"},
                {"BatteryCharge4", "&xE85E;"},
                {"BatteryCharge5", "&xE85F;"},
                {"BatteryCharge6", "&xE860;"},
                {"BatteryCharge7", "&xE861;"},
                {"BatteryCharge8", "&xE862;"},
                {"BatteryDisconnect", "&xE996;"},
                {"BatteryLarge0", "&xEBA0;"},
                {"BatteryLarge1", "&xEBA1;"},
                {"BatteryLarge10", "&xEBAA;"},
                {"BatteryLarge2", "&xEBA2;"},
                {"BatteryLarge3", "&xEBA3;"},
                {"BatteryLarge4", "&xEBA4;"},
                {"BatteryLarge5", "&xEBA5;"},
                {"BatteryLarge6", "&xEBA6;"},
                {"BatteryLarge7", "&xEBA7;"},
                {"BatteryLarge8", "&xEBA8;"},
                {"BatteryLarge9", "&xEBA9;"},
                {"BatteryLargeCharge0", "&xEBAB;"},
                {"BatteryLargeCharge1", "&xEBAC;"},
                {"BatteryLargeCharge10", "&xEBB5;"},
                {"BatteryLargeCharge2", "&xEBAD;"},
                {"BatteryLargeCharge3", "&xEBAE;"},
                {"BatteryLargeCharge4", "&xEBAF;"},
                {"BatteryLargeCharge5", "&xEBB0;"},
                {"BatteryLargeCharge6", "&xEBB1;"},
                {"BatteryLargeCharge7", "&xEBB2;"},
                {"BatteryLargeCharge8", "&xEBB3;"},
                {"BatteryLargeCharge9", "&xEBB4;"},
                {"BatteryLargeSave0", "&xEBB6;"},
                {"BatteryLargeSave1", "&xEBB7;"},
                {"BatteryLargeSave10", "&xEBC0;"},
                {"BatteryLargeSave2", "&xEBB8;"},
                {"BatteryLargeSave3", "&xEBB9;"},
                {"BatteryLargeSave4", "&xEBBA;"},
                {"BatteryLargeSave5", "&xEBBB;"},
                {"BatteryLargeSave6", "&xEBBC;"},
                {"BatteryLargeSave7", "&xEBBD;"},
                {"BatteryLargeSave8", "&xEBBE;"},
                {"BatteryLargeSave9", "&xEBBF;"},
                {"BatterySave0", "&xE863;"},
                {"BatterySave1", "&xE864;"},
                {"BatterySave2", "&xE865;"},
                {"BatterySave3", "&xE866;"},
                {"BatterySave4", "&xE867;"},
                {"BatterySave5", "&xE868;"},
                {"BatterySave6", "&xE869;"},
                {"BatterySave7", "&xE86A;"},
                {"BatterySave8", "&xE86B;"},
                {"BellOffOutline", "&xE7ED;"},
                {"BellOutline", "&xEA8F;"},
                {"Bluetooth", "&xE702;"},
                {"Boat", "&xEB48;"},
                {"BoatOutline", "&xE7E3;"},
                {"Book", "&xE82D;"},
                {"BookPlus", "&xE82E;"},
                {"BoxFourth", "&xE744;"},
                {"BoxFull", "&xE747;"},
                {"BoxHalfHorizontal", "&xE745;"},
                {"BoxHalfVertical", "&xE746;"},
                {"BoxSixteenth", "&xE743;"},
                {"BoxSmall", "&xE004;"},
                {"Bus", "&xEB47;"},
                {"BusOutline", "&xE806;"},
                {"Calculator", "&xE1D0;"},
                {"Calendar", "&xE163;"},
                {"CalendarDay", "&xE184;"},
                {"CalendarRepeat", "&xE161;"},
                {"CalendarReply", "&xE1DB;"},
                {"CalendarWeeks", "&xE162;"},
                {"Camera", "&xE114;"},
                {"CameraClicker", "&xE12D;"},
                {"CameraSwitch", "&xE124;"},
                {"Cancel", "&xE25B;"},
                {"Car", "&xE7EC;"},
                {"CarLeftOutline", "&xE811;"},
                {"CarRightOutline", "&xEA5E;"},
                {"CarSide", "&xEA8B;"},
                {"Cd", "&xE958;"},
                {"Cellphone", "&xE1C9;"},
                {"CellphoneTablet", "&xE8CC;"},
                {"CellphoneWireless", "&xE957;"},
                {"Check", "&xE001;"},
                {"CheckboxBlank", "&xE002;"},
                {"CheckboxBlankOutline", "&xE003;"},
                {"CheckboxCheck", "&xE005;"},
                {"CheckOutlineCheck", "&xE0A2;"},
                {"ChevronBoldDown", "&xE96E;"},
                {"ChevronBoldLeft", "&xE96F;"},
                {"ChevronBoldRight", "&xE970;"},
                {"ChevronBoldUp", "&xE96D;"},
                {"ChevronDown", "&xE011;"},
                {"ChevronLeft", "&xE00E;"},
                {"ChevronLeftCircle", "&xE760;"},
                {"ChevronRight", "&xE00F;"},
                {"ChevronRightCircle", "&xE761;"},
                {"ChevronUp", "&xE010;"},
                {"Chip", "&xE964;"},
                {"Clear", "&xE750;"},
                {"ClearSmall", "&xE925;"},
                {"Clipboard", "&xE77F;"},
                {"Clock", "&xE121;"},
                {"Close", "&xE106;"},
                {"ClosedCaption", "&xE190;"},
                {"Cloud", "&xE753;"},
                {"Compare", "&xE11E;"},
                {"Computer", "&xE211;"},
                {"ComputerTheme", "&xE771;"},
                {"Cone", "&xE98F;"},
                {"Console", "&xE756;"},
                {"Contact", "&xE12A;"},
                {"ContactSend", "&xE1D7;"},
                {"Controller", "&xE7FC;"},
                {"Crop", "&xE123;"},
                {"Cursor", "&xE1E3;"},
                {"CursorDefault", "&xE8B0;"},
                {"Delete", "&xE107;"},
                {"Dialer", "&xE75F;"},
                {"Diamond", "&xE18A;"},
                {"Direction", "&xE816;"},
                {"Disk", "&xE105;"},
                {"DiskAll", "&xEA35;"},
                {"DiskDownload", "&xE159;"},
                {"DiskEdit", "&xE28F;"},
                {"Divide", "&xE94A;"},
                {"Doppler", "&xE95A;"},
                {"DotsHorizontal", "&xE10C;"},
                {"DotsVertical", "&xE796;"},
                {"Download", "&xE118;"},
                {"EaseOfAccess", "&xE07F;"},
                {"Edit", "&xE104;"},
                {"Education", "&xE7BE;"},
                {"Email", "&xE119;"},
                {"EmailAddress", "&xE168;"},
                {"EmailForward", "&xE120;"},
                {"EmailForwardRtl", "&xE1A8;"},
                {"EmailOpened", "&xE166;"},
                {"EmailReply", "&xE172;"},
                {"EmailReplyall", "&xE165;"},
                {"EmailReplyallRtl", "&xE1F2;"},
                {"EmailReplyRtl", "&xE1AF;"},
                {"Emoji", "&xE170;"},
                {"EmojiGrin", "&xE11D;"},
                {"Equal", "&xE94E;"},
                {"Eraser", "&xE75C;"},
                {"EraserColor1", "&xE82B;"},
                {"EraserColor2", "&xE82C;"},
                {"Exclamation", "&xE171;"},
                {"File", "&xE132;"},
                {"FileHiddenOutline", "&xE295;"},
                {"FileMultiple", "&xE16F;"},
                {"FileOutline", "&xE160;"},
                {"FileOutlineUp", "&xE8E5;"},
                {"FilePrinterOutline", "&xE956;"},
                {"Filter", "&xE16E;"},
                {"Fingerprint", "&xE928;"},
                {"Firewall", "&xE83D;"},
                {"Flag", "&xEB4F;"},
                {"FlagOutline", "&xEB50;"},
                {"Flash", "&xE945;"},
                {"Flashlight", "&xE754;"},
                {"Folder", "&xE188;"},
                {"FolderMove", "&xE19C;"},
                {"FolderOutline", "&xE8B7;"},
                {"FolderPlus", "&xE1DA;"},
                {"FolderRefresh", "&xE1DF;"},
                {"FolderRefreshCancel", "&xE1DD;"},
                {"FolderUp", "&xE197;"},
                {"FormatBlockLeftDecrease", "&xE290;"},
                {"FormatBlockLeftIndent", "&xE291;"},
                {"FormatBlockRightDecrease", "&xE297;"},
                {"FormatBlockRightIncrease", "&xE298;"},
                {"FormatBold", "&xE19B;"},
                {"FormatFontSize", "&xE1C8;"},
                {"FormatFontSizeDecrease", "&xE1C6;"},
                {"FormatFontSizeIncrease", "&xE1C7;"},
                {"FormatTextCenter", "&xE1A1;"},
                {"FormatTextLeft", "&xE1A2;"},
                {"FormatTextRight", "&xE1A0;"},
                {"FormatUnderline", "&xE19A;"},
                {"Gps", "&xE1D2;"},
                {"Grid", "&xE80A;"},
                {"GridPerspective", "&xE809;"},
                {"Headphones", "&xE7F6;"},
                {"Headset", "&xE95B;"},
                {"Heart", "&xE00B;"},
                {"HeartBroken", "&xE007;"},
                {"HeartOutline", "&xE006;"},
                {"HeartPulse", "&xE95E;"},
                {"Help", "&xE11B;"},
                {"Home", "&xEA8A;"},
                {"HomeOutline", "&xE10F;"},
                {"HomeTree", "&xE1C3;"},
                {"Image", "&xEB9F;"},
                {"Indent", "&xE7FD;"},
                {"Info", "&xE946;"},
                {"InputMarker", "&xE193;"},
                {"InputMarkerColor1", "&xE891;"},
                {"InputMarkerColor2", "&xE82A;"},
                {"InputPen", "&xE76D;"},
                {"InputPenColor1", "&xE88F;"},
                {"InputPenColor2", "&xE829;"},
                {"Key", "&xE192;"},
                {"Keyboard", "&xE087;"},
                {"KeyboardDown", "&xE75B;"},
                {"KeyboardEnter", "&xE751;"},
                {"KeyboardLeft", "&xE763;"},
                {"KeyboardMouse", "&xE961;"},
                {"KeyboardRight", "&xE764;"},
                {"KeyboardSplit", "&xE08F;"},
                {"KeyboardUp", "&xE75A;"},
                {"Landmark", "&xE825;"},
                {"Laptop", "&xE770;"},
                {"LaptopMonitor", "&xE7F8;"},
                {"LaptopMonitorExtend", "&xE7F7;"},
                {"LaptopPrinter", "&xE772;"},
                {"LaptopTablet", "&xE212;"},
                {"Layers", "&xE81E;"},
                {"Led", "&xE781;"},
                {"Library", "&xE1D3;"},
                {"Lightbulb", "&xEA80;"},
                {"LineHorizontal", "&xE0B8;"},
                {"Link", "&xE167;"},
                {"List", "&xE292;"},
                {"ListBlock", "&xE15C;"},
                {"ListBlockRtl", "&xEA65;"},
                {"ListCheckRtl", "&xEA98;"},
                {"ListCollapse", "&xE16A;"},
                {"ListExpand", "&xE169;"},
                {"ListRtl", "&xE175;"},
                {"ListSelect", "&xE179;"},
                {"ListSelectRtl", "&xE1EC;"},
                {"ListSelectUp", "&xE17D;"},
                {"ListSelectUpRtl", "&xE1ED;"},
                {"Lock", "&xE1F6;"},
                {"Lowercase", "&xE84A;"},
                {"Magnify", "&xE1A3;"},
                {"MagnifyMinus", "&xE1A4;"},
                {"MagnifyPlus", "&xE12E;"},
                {"MapDownload", "&xE826;"},
                {"MapLocation", "&xE1C4;"},
                {"MapMarkerPause", "&xEB4A;"},
                {"MapMarkerPauseOutline", "&xE81A;"},
                {"MapMarkerPlay", "&xEB49;"},
                {"MapMarkerPlayOutline", "&xE819;"},
                {"MapPin", "&xE139;"},
                {"Media", "&xEA69;"},
                {"MediaFastforward", "&xEB9D;"},
                {"MediaNext", "&xE101;"},
                {"MediaPause", "&xE103;"},
                {"MediaPlay", "&xE102;"},
                {"MediaPlayer", "&xE955;"},
                {"MediaPrevious", "&xE100;"},
                {"MediaRepeat", "&xE1CA;"},
                {"MediaRewind", "&xEB9E;"},
                {"MediaServer", "&xE953;"},
                {"MediaWireless", "&xE952;"},
                {"Megaphone", "&xE789;"},
                {"Menu", "&xE700;"},
                {"Message", "&xE15F;"},
                {"MessageForwardRtl", "&xE89B;"},
                {"MessageMultiple", "&xE8F2;"},
                {"MessageProcessing", "&xE25C;"},
                {"MessageQuote", "&xE134;"},
                {"MessageVideo", "&xE13B;"},
                {"Microphone", "&xE1D6;"},
                {"Minus", "&xE108;"},
                {"Monitor", "&xE7F4;"},
                {"MonitorDuplicate", "&xE7F9;"},
                {"MonitorExtend", "&xE7FA;"},
                {"MonitorSound", "&xE7F3;"},
                {"MonitorTape", "&xE954;"},
                {"Moon", "&xE708;"},
                {"Mouse", "&xE962;"},
                {"Multiply", "&xE947;"},
                {"Music", "&xE189;"},
                {"Network", "&xE17B;"},
                {"NetworkClose", "&xE17A;"},
                {"Nfc", "&xE9A1;"},
                {"Note", "&xE70B;"},
                {"OpenInApp", "&xE17C;"},
                {"Outline", "&xE12F;"},
                {"OutlineRtl", "&xEA41;"},
                {"Palette", "&xE2B1;"},
                {"PanelBottom", "&xE147;"},
                {"PanelLeft", "&xE145;"},
                {"PanelRight", "&xE146;"},
                {"Pen", "&xE929;"},
                {"Percent", "&xE94C;"},
                {"Phone", "&xE13A;"},
                {"PhoneBook", "&xE1D4;"},
                {"PhoneForward", "&xE7F2;"},
                {"PhoneForwardRtl", "&xEA97;"},
                {"PhoneHangup", "&xE137;"},
                {"Pin", "&xE840;"},
                {"PinColor", "&xE842;"},
                {"PinLeft", "&xE141;"},
                {"PinLeftColor", "&xE841;"},
                {"Plus", "&xE109;"},
                {"PlusMinus", "&xE94D;"},
                {"Printer", "&xE2F6;"},
                {"Printer3d", "&xE2F7;"},
                {"Processor", "&xE950;"},
                {"Projector", "&xE95D;"},
                {"Puzzle", "&xEA86;"},
                {"Redo", "&xE10D;"},
                {"Refresh", "&xE117;"},
                {"Region", "&xE775;"},
                {"Remote", "&xE951;"},
                {"Rename", "&xE13E;"},
                {"Repeat", "&xE1CD;"},
                {"RepeatOnce", "&xE1CC;"},
                {"RotateClockwise", "&xE7AD;"},
                {"RotateLeft", "&xE14F;"},
                {"RotationLock", "&xE755;"},
                {"Router", "&xE965;"},
                {"RouterWireless", "&xE969;"},
                {"Scanner", "&xE294;"},
                {"Scissors", "&xE8C6;"},
                {"Sd", "&xE7F1;"},
                {"Search", "&xE094;"},
                {"Security", "&xE727;"},
                {"SecurityAlert", "&xE1DE;"},
                {"SelectionCut", "&xE924;"},
                {"SelectionRedo", "&xE1F4;"},
                {"SelectionUndo", "&xE1C5;"},
                {"SelectTable", "&xE14E;"},
                {"Send", "&xE122;"},
                {"Server", "&xE83B;"},
                {"ServerNetwork", "&xE968;"},
                {"Setting", "&xE115;"},
                {"Share", "&xE72D;"},
                {"Shuffle", "&xE14B;"},
                {"SidebarLeft_expand", "&xE1C0;"},
                {"SidebarLeftCollapse", "&xE1BF;"},
                {"SidebarRightCollapse", "&xE126;"},
                {"SidebarRightExpand", "&xE127;"},
                {"Signal1", "&xE86C;"},
                {"Signal2", "&xE86D;"},
                {"Signal3", "&xE86E;"},
                {"Signal4", "&xE86F;"},
                {"Signal5", "&xE870;"},
                {"SignalCancel", "&xE871;"},
                {"SlashForward", "&xE199;"},
                {"Sound", "&xE15D;"},
                {"Sound0", "&xE992;"},
                {"Sound1", "&xE993;"},
                {"Sound2", "&xE994;"},
                {"Sound3", "&xE995;"},
                {"SoundCancel", "&xE198;"},
                {"Space", "&xE75D;"},
                {"Speaker", "&xE7F5;"},
                {"SquareRoot", "&xE94B;"},
                {"Star", "&xE1CF;"},
                {"StarCancel", "&xE195;"},
                {"StarHalfLeft", "&xE7C6;"},
                {"StarHalfRight", "&xE7C7;"},
                {"StarOutline", "&xE1CE;"},
                {"Sun", "&xE706;"},
                {"Tablet", "&xE70A;"},
                {"Tag", "&xE1CB;"},
                {"Tape", "&xE96A;"},
                {"ThoughtBubble", "&xEA91;"},
                {"Thumbs", "&xE19D;"},
                {"ThumbsDown", "&xE19E;"},
                {"ThumbsUp", "&xE19F;"},
                {"Timer", "&xE916;"},
                {"Toolbox", "&xEB4E;"},
                {"ToolboxOutline", "&xE821;"},
                {"Tooltip", "&xE7E7;"},
                {"TooltipOutline", "&xE91C;"},
                {"Touch", "&xE815;"},
                {"TouchSlider", "&xE927;"},
                {"Tram", "&xEB4D;"},
                {"TramOutline", "&xE7C0;"},
                {"Translate", "&xE164;"},
                {"Undo", "&xE10E;"},
                {"Unlock", "&xE1F7;"},
                {"Upload", "&xE11C;"},
                {"Uppercase", "&xE84B;"},
                {"Usb", "&xE88E;"},
                {"Video", "&xE25D;"},
                {"VideoOutline", "&xE116;"},
                {"Voicemail", "&xE1D5;"},
                {"Walk", "&xE726;"},
                {"WalkOutline", "&xE805;"},
                {"Webcam", "&xE960;"},
                {"Wifi1", "&xE872;"},
                {"Wifi2", "&xE873;"},
                {"Wifi3", "&xE874;"},
                {"WifiOutline0", "&xE1E5;"},
                {"WifiOutline1", "&xE1E6;"},
                {"WifiOutline2", "&xE1E7;"},
                {"WifiOutline3", "&xE1E8;"},
                {"WifiOutline4", "&xE1E9;"},
                {"WindowCollapse", "&xE1D8;"},
                {"WindowExpand", "&xE1D9;"},
                {"Wireless", "&xE704;"},
                {"World", "&xE128;"},
                {"WorldWire", "&xE12B;"},
                {"Wrench", "&xE15E;"},
                {"Xbox", "&xE990;"},
            };
            DataContext = new Dictionary<string, string>(data);
        }

        private void TextBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            if (!string.IsNullOrEmpty(edSearch.Text))
            {
                string token = edSearch.Text.ToLower();
                DataContext = data.Where(A => A.Key.ToLower().Contains(token));
            }
            else
            {
                DataContext = new Dictionary<string, string>(data); 
            }
        }

        private void putclipboard(string val)
        {
            try
            {
                Clipboard.SetText(val);
            }
            catch (Exception)
            {
            }
        }

        private void CopyName(object sender, RoutedEventArgs e)
        {
            MenuItem item = e.OriginalSource as MenuItem;
            if (item != null && item.DataContext != null)
            {
                KeyValuePair<string, string> dat = (KeyValuePair<string, string>)item.DataContext;

                putclipboard("MDL2_" + dat.Key);
            }

        }

        private void CopyHex(object sender, RoutedEventArgs e)
        {
            MenuItem item = e.OriginalSource as MenuItem;
            if (item != null && item.DataContext != null)
            {
                KeyValuePair<string, string> dat = (KeyValuePair<string, string>)item.DataContext;

                putclipboard(dat.Value);
            }
        }

        private void CopyChar(object sender, RoutedEventArgs e)
        {

            MenuItem item = e.OriginalSource as MenuItem;
            if (item != null && item.DataContext != null)
            {
                KeyValuePair<string, string> dat = (KeyValuePair<string, string>)item.DataContext;

                putclipboard(new HexToCharValueConverter().Convert(dat.Value, null, null, null) as string);
            }
            
        }
    }
}
